# Generated by Django 6.0.5 on 2026-06-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='dealer_field',
        ),
    ]
